stages:
  - setup
  - build
  - test
  - synthesis
  - deploy

setup-runner:
  stage: setup
  script:
    - apt install make
    - make -v

build-job:
  stage: build
  script:
    - make ci-build
  artifacts:
    expire_in: 1 week
    paths:
      - internal/app/*/*.zip

test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

synthesize-cloudformation:
  stage: synthesis
  script:
    - echo "Synthesize Cloud Formation template"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
