image: alpine:latest

stages:
  - build
  - test
  - synthesis
  - acceptance-test
  - deploy

build-job:
  image: golang:latest
  stage: build
  before_script:
    - apt update
    - apt install zip -y
  script:
    - ./scripts/build.sh
  artifacts:
    expire_in: 1 week
    paths:
      - internal/app/*/*.zip

test-job1:
  image: golang:latest
  stage: test
  script:
    - echo "This job tests something"
    - go install gotest.tools/gotestsum@latest
    - gotestsum --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: report.xml

synthesize-cloudformation:
  stage: synthesis
  script:
    - echo "Synthesize Cloud Formation template"

test-localstack:
  stage: acceptance-test
  services:
    - name: docker:20.10.16-dind
      alias: docker
      command: ["--tls=false"]
  before_script:
    - apk update
    - apk add gcc musl-dev linux-headers py3-pip python3 python3-dev
    - python3 -m pip install localstack awscli
  script:
    - docker pull localstack/localstack:latest
    - dind_ip="$(getent hosts docker | cut -d' ' -f1)"
    - echo "${dind_ip} localhost.localstack.cloud " >> /etc/hosts
    - DOCKER_HOST="tcp://${dind_ip}:2375" localstack start -d
    - aws --endpoint http://localhost.localstack.cloud:4566 s3 mb s3://test
    - echo "hello world" > /tmp/hello-world
    - aws --endpoint http://localhost.localstack.cloud:4566 s3 cp /tmp/hello-world s3://test/hello-world
    - aws --endpoint http://localhost.localstack.cloud:4566 s3 ls s3://test/


deploy-staging:
  stage: deploy
  script:
    - echo "Deployment to staging"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  allow_failure: false
  rules:
    - when: manual
