image: alpine:latest

stages:
  - build
  - test
  - synthesis
  - localstack-deploy
  - acceptance-test
  - deploy

build-job:
  image: golang:latest
  stage: build
  script:
    - apt update
    - apt install zip -y
    - ./scripts/build.sh
  artifacts:
    expire_in: 1 week
    paths:
      - internal/app/*/*.zip

test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 5

synthesize-cloudformation:
  stage: synthesis
  script:
    - echo "Synthesize Cloud Formation template"

deploy-staging:
  stage: deploy
  script:
    - echo "Deployment to staging"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  allow_failure: false
  rules:
    - when: manual
